# QOL Commands Config
# Written by Jimmy Wallace (jombles/jamesw98)

# enabled commands
enableAtPlayer: true
enableLinks: true
enableStaff: false

# poke cooldown
cooldown: 30 # in seconds

# links values:
linkValues:
  discord: https://discord.gg/9PCdaWe
  donate: https://playandor.enjin.com/shop
  website: http://www.playandor.com/
  youtube: https://www.youtube.com/channel/UCY14YZvkw-qDFvs-7q1D87Q

# staff
staffList:
  - yacht
  - jombles
  - pine
  - fry

staffMembers:
  yacht:
    ign: Yacht_Crafter
    rank: Owner
    discord: YachtCrafter#6687
    item: OAK_BOAT
  jombles:
    ign: j0mbles
    rank: Admin
    discord: jombles#6380
    item: IRON_AXE
  pine:
    ign: PineCohn
    rank: Admin
    discord: Pine#0809
    item: SPRUCE_SAPLING
  fry:
    ign: Frytality
    rank: Moderator
    discord: Frytality#3817
    item: TURTLE_HELMET
